name = input("enter name:")
age = input("enter age :")
weight = input("enter weight:")
city = input("enter the city:")
reason = input("enter the reason:")
print("welcome",name)
print("this is your age-",age)
print("this is your weight-",weight)
print("this is your adress-",city)
print("this is the reason-",reason)
print("These were the some info that i have about you-- ")
print("Thank you-",name)